"""Paper figures, regenerated by one command (plan Section 11, Phase 6).

Every figure is built from tables already stored, so running this downloads nothing and
produces the same picture from the same data. A figure whose inputs are missing is skipped
and named, rather than drawn from whatever happens to be lying around.

Two habits are deliberate and apply to every chart here. Counts that rest on inferred
relationships, or on synthetic ASPA records, carry that in the title or the caption rather
than in a footnote somewhere else. And no axis starts anywhere but zero unless the chart says
so, because a truncated axis is the easiest way to make a small change look like a large one.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")  # no display on a build machine or in CI

import matplotlib.pyplot as plt  # noqa: E402
import polars as pl  # noqa: E402

from hijax.analysis.adoption import aspa_coverage_by_position  # noqa: E402
from hijax.analysis.longitudinal import build_series  # noqa: E402
from hijax.analysis.regional import compare_regions  # noqa: E402
from hijax.config import Config  # noqa: E402
from hijax.tables import (  # noqa: E402
    latest_snapshot,
    previous_month,
    read_partition,
    table_root,
)

#: One accessible palette, used consistently so the same thing is the same colour across
#: every figure in the paper.
COLOURS = {
    "primary": "#1f4e79",
    "secondary": "#c55a11",
    "muted": "#7f7f7f",
    "accent": "#2e7d32",
    "warn": "#8b1a1a",
}

TRUST_ANCHOR_COLOURS = {
    "ripe": "#1f4e79",
    "arin": "#c55a11",
    "apnic": "#2e7d32",
    "lacnic": "#8b1a1a",
    "afrinic": "#7f7f7f",
}


@dataclass(slots=True)
class ReportResult:
    """Which figures were drawn and which could not be."""

    written: list[Path] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)


def _style(ax: Any, title: str, xlabel: str, ylabel: str) -> None:
    ax.set_title(title, fontsize=11, loc="left", pad=10)
    ax.set_xlabel(xlabel, fontsize=9)
    ax.set_ylabel(ylabel, fontsize=9)
    ax.grid(True, axis="y", alpha=0.25, linewidth=0.6)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.tick_params(labelsize=8)


def _save(fig: Any, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(destination, dpi=200)
    plt.close(fig)
    return destination


def adoption_over_time(aspas_by_day: pl.DataFrame, destination: Path) -> Path:
    """RQ1: ASPA records published worldwide, week by week."""
    frame = aspas_by_day.sort("snapshot_date")
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    ax.plot(
        frame["snapshot_date"].to_list(),
        frame["aspas"].to_list(),
        color=COLOURS["primary"],
        linewidth=1.8,
    )
    ax.fill_between(
        frame["snapshot_date"].to_list(),
        frame["aspas"].to_list(),
        color=COLOURS["primary"],
        alpha=0.12,
    )
    _style(
        ax,
        "ASPA records published worldwide",
        "",
        "records in force",
    )
    ax.set_ylim(bottom=0)
    return _save(fig, destination)


def adoption_by_trust_anchor(by_ta: pl.DataFrame, destination: Path) -> Path:
    """RQ1: the same series split by the registry each record was published through."""
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    for ta in sorted(by_ta["ta"].unique().to_list()):
        part = by_ta.filter(pl.col("ta") == ta).sort("snapshot_date")
        if part.height == 0:
            continue
        ax.plot(
            part["snapshot_date"].to_list(),
            part["aspas"].to_list(),
            label=ta,
            linewidth=1.6,
            color=TRUST_ANCHOR_COLOURS.get(str(ta), COLOURS["muted"]),
        )
    _style(ax, "ASPA records by regional registry", "", "records in force")
    ax.set_ylim(bottom=0)
    ax.legend(frameon=False, fontsize=8, ncol=5)
    return _save(fig, destination)


def rpki_coverage_over_time(vrps_by_day: pl.DataFrame, destination: Path) -> Path:
    """Context for RQ1: signed origin records over the same period."""
    frame = vrps_by_day.sort("snapshot_date")
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    ax.plot(
        frame["snapshot_date"].to_list(),
        [v / 1_000_000 for v in frame["vrps"].to_list()],
        color=COLOURS["secondary"],
        linewidth=1.8,
    )
    _style(
        ax,
        "Signed origin records (VRPs) over the same period",
        "",
        "millions of records",
    )
    ax.set_ylim(bottom=0)
    return _save(fig, destination)


def path_coverage(shares: dict[str, float], destination: Path) -> Path:
    """RQ1: where an ASPA publisher sits on a path, which decides what it can do."""
    order = ["any", "transit", "neighbour", "origin", "adjacent_pair", "all_hops"]
    labels = {
        "any": "anywhere on the path",
        "transit": "somewhere in transit",
        "neighbour": "at the collector's peer",
        "origin": "at the origin",
        "adjacent_pair": "two publishers adjacent",
        "all_hops": "every hop covered",
    }
    keys = [k for k in order if k in shares]
    values = [shares[k] * 100 for k in keys]
    colours = [
        COLOURS["accent"] if k in ("adjacent_pair", "all_hops") else COLOURS["primary"]
        for k in keys
    ]

    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    bars = ax.barh([labels[k] for k in keys], values, color=colours, height=0.62)
    for bar, value in zip(bars, values, strict=True):
        ax.text(
            bar.get_width() + 0.6,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.2f}%" if value < 1 else f"{value:.1f}%",
            va="center",
            fontsize=8,
            color=COLOURS["muted"],
        )
    _style(
        ax,
        "Where ASPA publishers sit on observed paths\n"
        "Only two adjacent publishers can confirm a hop,\n"
        "which is why most routes come out Unknown",
        "share of routes (%)",
        "",
    )
    ax.invert_yaxis()
    ax.set_xlim(0, max(values) * 1.25 if values else 1)
    return _save(fig, destination)


def counterfactual_blocking(summary: pl.DataFrame, destination: Path) -> Path:
    """RQ3: share of detected leaks stopped, by who publishes and who filters."""
    frame = summary.sort(["publication", "filtering"])
    publications = sorted(frame["publication"].unique().to_list())
    filterings = sorted(frame["filtering"].unique().to_list())

    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    width = 0.8 / max(len(filterings), 1)
    for index, filtering in enumerate(filterings):
        part = frame.filter(pl.col("filtering") == filtering)
        lookup = {row["publication"]: row["blocked_share"] for row in part.iter_rows(named=True)}
        positions = [i + index * width for i in range(len(publications))]
        ax.bar(
            positions,
            [lookup.get(p, 0.0) * 100 for p in publications],
            width=width,
            label=str(filtering),
            color=[COLOURS["primary"], COLOURS["secondary"], COLOURS["muted"]][index % 3],
        )

    upper_bound = {
        row["publication"] for row in frame.iter_rows(named=True) if row["upper_bound_only"]
    }
    labels = [f"{p}*" if p in upper_bound else str(p) for p in publications]
    ax.set_xticks([i + 0.4 - width / 2 for i in range(len(publications))])
    ax.set_xticklabels(labels)
    _style(
        ax,
        "Share of detected leaks that would have been blocked\n"
        "* upper bound only: synthetic records restate the topology used to find the leaks",
        "who has published ASPA records",
        "leaks blocked (%)",
    )
    ax.set_ylim(0, 100)
    ax.legend(frameon=False, fontsize=8, title="who filters", title_fontsize=8)
    return _save(fig, destination)


def regional_comparison(comparison: pl.DataFrame, destination: Path) -> Path:
    """RQ4: India and the APNIC region against the world."""
    frame = comparison
    regions = frame["region"].to_list()
    shares = [s * 100 for s in frame["share_of_routed"].to_list()]

    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    bars = ax.bar(
        regions,
        shares,
        color=[COLOURS["muted"], COLOURS["secondary"], COLOURS["primary"]][: len(regions)],
        width=0.55,
    )
    for bar, value in zip(bars, shares, strict=True):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + max(shares) * 0.03,
            f"{value:.2f}%",
            ha="center",
            fontsize=9,
        )
    _style(
        ax,
        "Routed networks publishing an ASPA record\n"
        "Country means country of registration, not where the network operates",
        "",
        "share of routed networks (%)",
    )
    ax.set_ylim(0, max(shares) * 1.3 if shares else 1)
    return _save(fig, destination)


# ---------------------------------------------------------------------------------------
# Pulling the inputs together
# ---------------------------------------------------------------------------------------


def validation_over_time(series: pl.DataFrame, destination: Path) -> Path:
    """RQ1 over time: what share of routes each validator could judge, quarter by quarter.

    Plotted as shares rather than counts, because the routing table grew over the period and
    counts would conflate growth with adoption.
    """
    frame = series.sort("snapshot_date")
    days = frame["snapshot_date"].to_list()

    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    lines = [
        ("rov_valid", "ROV Valid", COLOURS["accent"], "-"),
        ("rov_invalid", "ROV Invalid", COLOURS["warn"], "-"),
        ("aspa_valid", "ASPA Valid", COLOURS["primary"], "--"),
        ("aspa_invalid", "ASPA Invalid", COLOURS["secondary"], "--"),
    ]
    drawn = False
    for column, label, colour, style in lines:
        if column not in frame.columns:
            continue
        raw = frame[column].to_list()
        if all(v is None for v in raw):
            continue
        # NaN rather than None so a missing quarter draws as a gap in the line.
        values = [float("nan") if v is None else float(v) * 100 for v in raw]
        ax.plot(days, values, label=label, color=colour, linestyle=style, linewidth=1.8)
        drawn = True
    if not drawn:
        raise ValueError("no validation states to plot")

    _style(
        ax,
        "Share of routes in each validation state\n"
        "Quarterly, route-views2 only; ASPA Unknown dominates and is omitted for scale",
        "",
        "share of routes (%)",
    )
    ax.set_ylim(bottom=0)
    ax.legend(fontsize=8, frameon=False, ncol=2)
    return _save(fig, destination)


def _load_routes(cfg: Config, day: date) -> pl.DataFrame | None:
    """Read every collector's routes for one date, for the cross-sectional figures."""
    return read_partition(
        table_root(cfg, "routes"), day, "routes.parquet", ["as_path", "origin_asn"]
    )


def build_all(cfg: Config, *, destination: Path | None = None) -> ReportResult:
    """Regenerate every figure the stored data can support."""
    out = destination or cfg.paths.figures
    result = ReportResult()

    aspas_glob = cfg.paths.processed / "aspas" / "snapshot_date=*" / "aspas.parquet"
    try:
        aspas = pl.read_parquet(str(aspas_glob))
    except Exception:  # noqa: BLE001 - absence is reported, not raised
        aspas = None
        result.skipped.append(("adoption", "no ingested ASPA snapshots"))

    if aspas is not None:
        by_day = aspas.group_by("snapshot_date").agg(pl.len().alias("aspas")).sort("snapshot_date")
        result.written.append(adoption_over_time(by_day, out / "aspa_adoption_over_time.png"))
        by_ta = (
            aspas.group_by(["snapshot_date", "ta"])
            .agg(pl.len().alias("aspas"))
            .sort(["snapshot_date", "ta"])
        )
        result.written.append(
            adoption_by_trust_anchor(by_ta, out / "aspa_adoption_by_registry.png")
        )

    vrps_glob = cfg.paths.processed / "vrps" / "snapshot_date=*" / "vrps.parquet"
    try:
        vrps = pl.read_parquet(str(vrps_glob), columns=["snapshot_date"])
        by_day = vrps.group_by("snapshot_date").agg(pl.len().alias("vrps")).sort("snapshot_date")
        result.written.append(rpki_coverage_over_time(by_day, out / "rpki_coverage_over_time.png"))
    except Exception:  # noqa: BLE001
        result.skipped.append(("rpki coverage", "no ingested VRP snapshots"))

    latest_routes = latest_snapshot(table_root(cfg, "routes"))
    routes = _load_routes(cfg, latest_routes) if latest_routes is not None else None
    if latest_routes is None:
        result.skipped.append(("path coverage and regional", "no ingested routes"))
    elif routes is None:
        # A partition directory can exist with no readable table in it, for instance after an
        # interrupted ingest. That is a missing input and must be named, not passed over.
        result.skipped.append(
            ("path coverage and regional", f"no readable routes for {latest_routes}")
        )
    elif aspas is None:
        result.skipped.append(("path coverage and regional", "no ingested ASPA records"))
    else:
        publishers = {
            int(a) for a in aspas.filter(pl.col("snapshot_date") == latest_routes)["customer_asn"]
        } or {int(a) for a in aspas["customer_asn"]}

        coverage = aspa_coverage_by_position(routes.select("as_path"), publishers)
        result.written.append(path_coverage(coverage["shares"], out / "aspa_path_coverage.png"))

        meta_month = previous_month(latest_routes)
        meta_path = cfg.paths.processed / "as_meta" / f"month={meta_month}" / "as_meta.parquet"
        if meta_path.exists():
            routed = {
                int(a) for a in routes.select("origin_asn").drop_nulls()["origin_asn"].unique()
            }
            comparison = compare_regions(pl.read_parquet(meta_path), publishers, routed)
            result.written.append(regional_comparison(comparison, out / "regional_comparison.png"))
        else:
            result.skipped.append(("regional", f"no as_meta for {meta_month}"))

    series = build_series(cfg)
    if series.height >= 2:
        try:
            result.written.append(validation_over_time(series, out / "validation_over_time.png"))
        except ValueError as exc:
            result.skipped.append(("validation over time", str(exc)))
    else:
        result.skipped.append(
            ("validation over time", f"only {series.height} validated date(s); needs 2+")
        )

    counter = cfg.paths.processed / "counterfactual"
    latest_cf = latest_snapshot(table_root(cfg, "counterfactual"))
    if latest_cf is not None:
        frame = pl.read_parquet(
            counter / f"snapshot_date={latest_cf:%Y-%m-%d}" / "counterfactual.parquet"
        )
        result.written.append(counterfactual_blocking(frame, out / "counterfactual_blocking.png"))
    else:
        result.skipped.append(("counterfactual", "run 'hijax counterfactual' first"))

    return result
